### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by amberfbrown** [amberfbrown/prework-study-guide#3]
#JavaScript

## User Story
As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

## Acceptance Criteria
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by GARY121github** [comment]
```
<!DOCTYPE html>
<html>
<head>
    <title>Prework Study Guide</title>
</head>
<body>
    <h1>Prework Study Guide</h1>

    <h2>Topics</h2>
    <ul>
        <li>Topic 1: [Insert topic name]</li>
        <li>Topic 2: [Insert topic name]</li>
        <li>Topic 3: [Insert topic name]</li>
        <li>Topic 4: [Insert topic name]</li>
    </ul>

    <h2>Suggested Study Order</h2>
    <ol>
        <li>Start with [Insert suggested topic to study first].</li>
        <li>Next, study [Insert suggested topic to study second].</li>
        <li>Continue with [Insert suggested topic to study third].</li>
        <li>Lastly, study [Insert suggested topic to study fourth].</li>
    </ol>
</body>
</html>
```

You can customize this template by replacing [Insert topic name] with the actual names of the topics you learned during the boot camp prework. Similarly, replace [Insert suggested topic to study first] and other placeholders with the appropriate suggestions based on the order in which you recommend studying the topics.

Once you have customized the template with your specific information, you can save it with a .html extension and open it in a web browser to view the prework study guide webpage.
